package GUI;

import OBJ.SanPham;
import Utils.ValidateData;
import java.awt.Window;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

public class frmSanPham extends javax.swing.JPanel {

    private DefaultTableModel defaultTableModel;
    SanPham sp = new SanPham();
    static ArrayList<SanPham> listSP = new ArrayList<>();
    ValidateData validate = new ValidateData();

    /**
     * Creates new form frmSanPham
     */
    public frmSanPham() {
        initComponents();
        loadFile();
        getData(listSP);
    }

    public void loadFile() {
        try {
            BufferedReader br = null;
            FileReader fr = null;
            listSP = new ArrayList<>(); //lưu ý
            fr = new FileReader("sanpham.txt");
            br = new BufferedReader(fr);
            String s = null;

            try {
                while ((s = br.readLine()) != null) {
                    //Cắt chuỗi:
                    String arr[] = s.split("\t");
                    //Khởi tạo
                    SanPham sp = new SanPham();
                    sp.setMaSP(arr[0]);
                    sp.setTenSP(arr[1]);
                    sp.setDonViTinh(arr[2]);
                    sp.setTenNSX(arr[3]);
                    sp.setGiaNhap(Double.parseDouble(arr[4]));
                    sp.setGiaBan(Double.parseDouble(arr[5]));
                    sp.setSoLuong(Long.parseLong(arr[6]));
                    listSP.add(sp);
                }
            } catch (IOException ex) {
                Logger.getLogger(frmSanPham.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(frmSanPham.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void getData(ArrayList<SanPham> listSP) {
        defaultTableModel = new DefaultTableModel();
        defaultTableModel.addColumn("Mã SP");
        defaultTableModel.addColumn("Tên SP");
        defaultTableModel.addColumn("Đơn vị tính");
        defaultTableModel.addColumn("Tên NSX");
        defaultTableModel.addColumn("Giá bán");
        defaultTableModel.addColumn("Giá nhập");
        defaultTableModel.addColumn("Số lượng");

        for (SanPham obj : listSP) {
            Vector vector = new Vector();
            vector.add(obj.getMaSP());
            vector.add(obj.getTenSP());
            vector.add(obj.getDonViTinh());
            vector.add(obj.getTenNSX());
            vector.add(obj.getGiaNhap());
            vector.add(obj.getGiaBan());
            vector.add(obj.getSoLuong());
            defaultTableModel.addRow(vector);
        }
        tbl_sanPham.setModel(defaultTableModel);
    }

    public void saveFile() {

        try {
            BufferedWriter bw = null; //Khởi tạo
            FileWriter fw = null; //Khởi tạo
            String data = ""; //Tạo một string data bằng rỗng.
            for (int i = 0; i < listSP.size(); i++) {
                String row = ""; //tạo hàng rỗng
                row = row + listSP.get(i).getMaSP() + "\t";
                row = row + listSP.get(i).getTenSP() + "\t";
                row = row + listSP.get(i).getDonViTinh() + "\t";
                row = row + listSP.get(i).getTenNSX() + "\t";
                row = row + listSP.get(i).getGiaNhap() + "\t";
                row = row + listSP.get(i).getGiaBan() + "\t";
                row = row + listSP.get(i).getSoLuong() + "\n";
                data += row;
            }
            fw = new FileWriter("sanpham.txt");
            bw = new BufferedWriter(fw);
            bw.write(data);
            bw.close();
        } catch (IOException ex) {
            Logger.getLogger(frmSanPham.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void reset() {
        txt_donViTinh.setText("");
        txt_giaBan.setText("");
        txt_giaNhap.setText("");
        txt_maSP.setText("");
        txt_soLuong.setText("");
        txt_tenNSX.setText("");
        txt_tenSP.setText("");
        btn_suaSP.setEnabled(true);
        btn_themSP.setEnabled(true);
        btn_xoaSP.setEnabled(true);
        txt_tuKhoa.setText("");
        getData(listSP);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_sanPham = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_maSP = new javax.swing.JTextField();
        txt_donViTinh = new javax.swing.JTextField();
        txt_giaNhap = new javax.swing.JTextField();
        txt_soLuong = new javax.swing.JTextField();
        btn_themSP = new javax.swing.JButton();
        btn_suaSP = new javax.swing.JButton();
        btn_xoaSP = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txt_tuKhoa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_tenSP = new javax.swing.JTextField();
        txt_tenNSX = new javax.swing.JTextField();
        txt_giaBan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setLayout(null);

        tbl_sanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_sanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_sanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_sanPham);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 330, 1154, 349);

        jLabel1.setText("Mã Sản phẩm");
        add(jLabel1);
        jLabel1.setBounds(33, 48, 82, 16);

        jLabel2.setText("Đơn vị tính");
        add(jLabel2);
        jLabel2.setBounds(33, 94, 61, 16);

        jLabel3.setText("Giá nhập");
        add(jLabel3);
        jLabel3.setBounds(33, 142, 82, 16);

        jLabel4.setText("Số lượng");
        add(jLabel4);
        jLabel4.setBounds(33, 194, 82, 16);

        txt_maSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maSPActionPerformed(evt);
            }
        });
        add(txt_maSP);
        txt_maSP.setBounds(147, 45, 153, 22);
        add(txt_donViTinh);
        txt_donViTinh.setBounds(147, 91, 153, 22);
        add(txt_giaNhap);
        txt_giaNhap.setBounds(147, 139, 155, 22);

        txt_soLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_soLuongActionPerformed(evt);
            }
        });
        add(txt_soLuong);
        txt_soLuong.setBounds(147, 191, 155, 22);

        btn_themSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btn_themSP.setText("Thêm");
        btn_themSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themSPActionPerformed(evt);
            }
        });
        add(btn_themSP);
        btn_themSP.setBounds(746, 99, 85, 25);

        btn_suaSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        btn_suaSP.setText("Sửa");
        btn_suaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaSPActionPerformed(evt);
            }
        });
        add(btn_suaSP);
        btn_suaSP.setBounds(880, 99, 85, 25);

        btn_xoaSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btn_xoaSP.setText("Xóa");
        btn_xoaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaSPActionPerformed(evt);
            }
        });
        add(btn_xoaSP);
        btn_xoaSP.setBounds(746, 148, 85, 25);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        jButton4.setText("Thoát");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(880, 148, 85, 25);

        txt_tuKhoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_tuKhoaKeyReleased(evt);
            }
        });
        add(txt_tuKhoa);
        txt_tuKhoa.setBounds(871, 45, 183, 22);
        add(jLabel5);
        jLabel5.setBounds(1142, 261, 0, 0);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search.png"))); // NOI18N
        jButton1.setText("Tìm Kiếm");
        add(jButton1);
        jButton1.setBounds(746, 44, 107, 25);

        jLabel6.setText("Tên NSX");
        add(jLabel6);
        jLabel6.setBounds(386, 93, 50, 16);

        jLabel7.setText("Tên SP");
        add(jLabel7);
        jLabel7.setBounds(386, 48, 41, 16);

        jLabel8.setText("Giá Bán");
        add(jLabel8);
        jLabel8.setBounds(386, 152, 60, 16);
        add(txt_tenSP);
        txt_tenSP.setBounds(462, 45, 190, 22);
        add(txt_tenNSX);
        txt_tenNSX.setBounds(462, 90, 190, 22);
        add(txt_giaBan);
        txt_giaBan.setBounds(462, 149, 190, 22);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Background-xanh-lá-cây-nhạt.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        add(jLabel9);
        jLabel9.setBounds(-9, -4, 1160, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_soLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_soLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_soLuongActionPerformed

    private void txt_maSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maSPActionPerformed
    public boolean kiemTraMaSP(String ma) {
        for (int i = 0; i < listSP.size(); i++) {
            if (listSP.get(i).getMaSP().equals(ma)) {
                return false;
            }
        }
        return true;
    }
    private void btn_themSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themSPActionPerformed
        // TODO add your handling code here:
        String maSP = txt_maSP.getText();
        if (maSP.equals("")) {
            JOptionPane.showMessageDialog(this, "Mã sản phẩm không được để trống");
            return;
        } else if (!kiemTraMaSP(maSP)) {
            JOptionPane.showMessageDialog(this, "MÃ sản phẩm đã tồn tại");
            return;
        }
        String donViTinh = txt_donViTinh.getText();
        String tenSP = txt_tenSP.getText();
        String tenNSX = txt_tenNSX.getText();
        long soLuong = Long.parseLong(txt_soLuong.getText());
        double giaNhap = Double.parseDouble(txt_giaNhap.getText());
        double giaBan = Double.parseDouble(txt_giaBan.getText());
        if (txt_soLuong.equals("")) {
            JOptionPane.showMessageDialog(this, "Số lượng ko đc để trống");
            return;
        } else if (soLuong <= 0) {
            JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn 0");
            return;
        }

        if (txt_giaBan.equals("")) {
            JOptionPane.showMessageDialog(this, "giá nhập ko đc để trống");
            return;
        } else if (giaBan <= 0) {
            JOptionPane.showMessageDialog(this, "Giá bán phải lớn hơn 0");
            return;
        }
        if (txt_giaNhap.equals("")) {
            JOptionPane.showMessageDialog(this, "Giá nhập ko đc để trống");
            return;
        }
        if (giaNhap <= 0) {
            JOptionPane.showMessageDialog(this, "Giá nhập phải lớn hơn 0");
            return;
        }
        SanPham sp = new SanPham();
        sp.setMaSP(maSP);
        sp.setTenSP(tenSP);
        sp.setDonViTinh(donViTinh);
        sp.setTenNSX(tenNSX);
        sp.setSoLuong(soLuong);
        sp.setGiaBan(giaBan);
        sp.setGiaNhap(giaNhap);
        sp.setSoLuong(soLuong);
        listSP.add(sp);
        saveFile();
        getData(listSP);
        JOptionPane.showMessageDialog(this, "Thêm sản phẩm thành công");
        reset();
    }//GEN-LAST:event_btn_themSPActionPerformed

    private void txt_tuKhoaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tuKhoaKeyReleased
        // TODO add your handling code here:
        String tuKhoa = txt_tuKhoa.getText();
        if (tuKhoa.equals("")) {
            getData(listSP);
        } else {
            ArrayList<SanPham> listTimKiem = new ArrayList<>();
            for (int i = 0; i < listSP.size(); i++) {
                if (listSP.get(i).getMaSP().contains(tuKhoa)) {
                    listTimKiem.add(listSP.get(i));
                }
            }
            getData(listTimKiem);
        }
    }//GEN-LAST:event_txt_tuKhoaKeyReleased
    int index;
    private void tbl_sanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_sanPhamMouseClicked
        // TODO add your handling code here:
         int row = tbl_sanPham.getSelectedRow();
        String maSP = tbl_sanPham.getValueAt(row, 0).toString();
        
        for (int i = 0; i < listSP.size(); i++) {
            if (maSP.equals(listSP.get(i).getMaSP())) {
                sp = listSP.get(i);
                index = i;
                break;
            }
        }
        txt_maSP.setEnabled(false);
        txt_maSP.setText(sp.getMaSP());
        txt_tenSP.setText(sp.getTenSP());
        txt_donViTinh.setText(sp.getDonViTinh());
        txt_tenNSX.setText(sp.getTenNSX());
        txt_giaBan.setText(Double.toString(sp.getGiaBan()));
        txt_giaNhap.setText(Double.toString(sp.getGiaNhap()));
        txt_soLuong.setText(Long.toString(sp.getSoLuong()));
        btn_themSP.setEnabled(false);
    }//GEN-LAST:event_tbl_sanPhamMouseClicked

    private void btn_suaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaSPActionPerformed
        // TODO add your handling code here:
        String maSP = txt_maSP.getText();
  
        String donViTinh = txt_donViTinh.getText();
        String tenSP = txt_tenSP.getText();
        String tenNSX = txt_tenNSX.getText();
        long soLuong = Long.parseLong(txt_soLuong.getText());
        double giaNhap = Double.parseDouble(txt_giaNhap.getText());
        double giaBan = Double.parseDouble(txt_giaBan.getText());
        if (txt_soLuong.equals("")) {
            JOptionPane.showMessageDialog(this, "Số lượng ko đc để trống");
            return;
        } else if (soLuong <= 0) {
            JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn 0");
            return;
        }

        if (txt_giaBan.equals("")) {
            JOptionPane.showMessageDialog(this, "giá nhập ko đc để trống");
            return;
        } else if (giaBan <= 0) {
            JOptionPane.showMessageDialog(this, "Giá bán phải lớn hơn 0");
            return;
        }
        if (txt_giaNhap.equals("")) {
            JOptionPane.showMessageDialog(this, "Giá nhập ko đc để trống");
            return;
        }
        if (giaNhap <= 0) {
            JOptionPane.showMessageDialog(this, "Giá nhập phải lớn hơn 0");
            return;
        }
        SanPham sp = new SanPham();
        sp.setMaSP(maSP);
        sp.setTenSP(tenSP);
        sp.setDonViTinh(donViTinh);
        sp.setTenNSX(tenNSX);
        sp.setSoLuong(soLuong);
        sp.setGiaBan(giaBan);
        sp.setGiaNhap(giaNhap);
        sp.setSoLuong(soLuong);
        listSP.set(index, sp);
        saveFile();
        getData(listSP);
        JOptionPane.showMessageDialog(this, "Sửa sản phẩm thành công");
        reset();
    }//GEN-LAST:event_btn_suaSPActionPerformed

    private void btn_xoaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaSPActionPerformed
        // TODO add your handling code here:
        Integer confirm = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa không?", "Xóa", 2);
        if (confirm == JOptionPane.YES_OPTION) {
            if (listSP.remove(sp)) {
                saveFile();
                getData(listSP);
                reset();
                JOptionPane.showMessageDialog(this, "Xóa thành công ");
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại");
            }

        }
  
    }//GEN-LAST:event_btn_xoaSPActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JComponent comp = (JComponent) evt.getSource();
        Window win = SwingUtilities.getWindowAncestor(comp);
        win.dispose();
        frmMain main = new frmMain();
        main.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_suaSP;
    private javax.swing.JButton btn_themSP;
    private javax.swing.JButton btn_xoaSP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_sanPham;
    private javax.swing.JTextField txt_donViTinh;
    private javax.swing.JTextField txt_giaBan;
    private javax.swing.JTextField txt_giaNhap;
    private javax.swing.JTextField txt_maSP;
    private javax.swing.JTextField txt_soLuong;
    private javax.swing.JTextField txt_tenNSX;
    private javax.swing.JTextField txt_tenSP;
    private javax.swing.JTextField txt_tuKhoa;
    // End of variables declaration//GEN-END:variables
}
